import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'km';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

// Basic translations object
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    'dashboard': 'Dashboard',
    'orders': 'Orders',
    'pos': 'Smach Cafe POS',
    'inventory': 'Inventory',
    'income_expense': 'Income & Expense',
    'reports': 'Reports',
    'customers': 'Customers',
    'settings': 'Settings',
    'welcome': 'Welcome',
    'logout': 'Logout',
    'login': 'Login',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'add': 'Add',
    'loading': 'Loading',
    'dark_mode': 'Dark Mode',
    'language': 'Language',
    'appearance': 'Appearance',
    // Extended translations
    'sign_in': 'Sign in',
    'username': 'Username',
    'password': 'Password',
    'demo_credentials': 'Demo Credentials',
    'admin': 'Admin',
    'staff': 'Staff',
    'signing_in': 'Signing in...',
    'total_revenue': 'Total Revenue',
    'total_expenses': 'Total Expenses',
    'net_profit': 'Net Profit',
    'low_stock_alerts': 'Low Stock Alerts',
    'no_low_stock': 'No low stock alerts',
    'quick_actions': 'Quick Actions',
    'active_orders': 'active orders',
    'no_orders_found': 'No orders found',
    'table': 'Table',
    'status': 'Status',
    'payment_status': 'Payment Status',
    'total': 'Total',
    'actions': 'Actions',
    'process_payment': 'Process Payment',
    'print_receipt': 'Print Receipt',
    'confirm': 'Confirm',
    'are_you_sure': 'Are you sure?',
    'name': 'Name',
    'category': 'Category',
    'price': 'Price',
    'stock': 'Stock',
    'low_stock_threshold': 'Low Stock Threshold',
    'description': 'Description',
    'amount': 'Amount',
    'date': 'Date',
    'type': 'Type',
    'income': 'Income',
    'expense': 'Expense',
    'filter': 'Filter',
    'search': 'Search',
    'clear': 'Clear',
    'close': 'Close',
    'back': 'Back',
    'next': 'Next',
    'previous': 'Previous',
    'submit': 'Submit',
    'reset': 'Reset',
    'update': 'Update',
    'create': 'Create',
    'remove': 'Remove',
    'select': 'Select',
    'choose': 'Choose',
    'upload': 'Upload',
    'download': 'Download',
    'export': 'Export',
    'import': 'Import',
    'view': 'View',
    'hide': 'Hide',
    'show': 'Show',
    'open': 'Open',
    'new': 'New',
    'old': 'Old',
    'all': 'All',
    'none': 'None',
    'yes': 'Yes',
    'no': 'No',
    'ok': 'OK',
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'info': 'Info',
    'pending': 'Pending',
    'completed': 'Completed',
    'cancelled': 'Cancelled',
    'paid': 'Paid',
    'unpaid': 'Unpaid',
    'partial': 'Partial',
    'preparing': 'Preparing',
    'ready': 'Ready',
    // Dashboard specific
    'todays_transactions': 'Today\'s Transactions',
    'todays_orders': 'Today\'s Orders',
    'monthly_summary': 'Monthly Summary',
    'total_revenue_label': 'Total Revenue:',
    'total_expenses_label': 'Total Expenses:',
    'orders_label': 'Orders:',
    'net_profit_label': 'Net Profit:',
    'low_stock_alerts_title': 'Low Stock Alerts',
    'no_low_stock_alerts': 'No low stock alerts',
    'quick_actions_title': 'Quick Actions',
    'new_order': 'New Order',
    'add_product': 'Add Product',
    'view_reports': 'View Reports',
    'refresh': 'Refresh',
    'left': 'left',
    'min': 'Min',
    // Inventory specific
    'add_product_modal': 'Add Product',
    'edit_product_modal': 'Edit Product',
    'product_name': 'Product Name',
    'product_price': 'Product Price',
    'product_stock': 'Product Stock',
    'product_category': 'Product Category',
    'product_description': 'Product Description',
    'product_image': 'Product Image',
    'low_stock_threshold_label': 'Low Stock Threshold',
    'product_options': 'Product Options',
    'add_option': 'Add Option',
    'option_name': 'Option Name',
    'option_type': 'Option Type',
    'option_values': 'Option Values',
    'add_value': 'Add Value',
    'remove_option': 'Remove Option',
    'manage_categories': 'Manage Categories',
    'add_category': 'Add Category',
    'category_name': 'Category Name',
    'delete_product': 'Delete Product',
    'delete_product_confirm': 'Are you sure you want to delete this product?',
    'product_has_orders': 'This product has orders and cannot be deleted.',
    'product_orders_count': 'This product is used in {count} orders.',
    'filter_by_category': 'Filter by Category',
    'all_categories': 'All Categories',
    'search_products': 'Search products...',
    'no_products_found': 'No products found',
    'product_created': 'Product created successfully',
    'product_updated': 'Product updated successfully',
    'product_deleted': 'Product deleted successfully',
    'error_creating_product': 'Error creating product',
    'error_updating_product': 'Error updating product',
    'error_deleting_product': 'Error deleting product',
    'error_loading_products': 'Error loading products',
    'error_loading_categories': 'Error loading categories',
    'error_saving_categories': 'Error saving categories',
    'category_created': 'Category created successfully',
    'category_updated': 'Category updated successfully',
    'category_deleted': 'Category deleted successfully',
    'duplicate_category': 'Category already exists',
    'invalid_category_name': 'Please enter a valid category name',
    'required_field': 'This field is required',
    'invalid_price': 'Please enter a valid price',
    'invalid_stock': 'Please enter a valid stock quantity',
    'invalid_low_stock_threshold': 'Please enter a valid low stock threshold',
    'image_upload_error': 'Error uploading image',
    'image_too_large': 'Image file is too large',
    'invalid_image_format': 'Invalid image format',
    'loading_products': 'Loading products...',
    'saving_product': 'Saving product...',
    'deleting_product': 'Deleting product...',
    'loading_categories': 'Loading categories...',
    'saving_categories': 'Saving categories...',
    'basic_information': 'Basic Information',
    'total_customers': 'Total Customers',
    'total_loyalty_points': 'Total Loyalty Points',
    'avg_points_per_customer': 'Avg Points per Customer',
    'loyalty_points': 'Loyalty Points',
    'member_card': 'Member Card',
    'phone': 'Phone',
    'manage_points': 'Manage Points',
    'add_new_customer': 'Add New Customer',
    'manage_loyalty_points': 'Manage Loyalty Points',
    'current_points': 'Current Points',
    'operation': 'Operation',
    'add_points': 'Add Points',
    'subtract_points': 'Subtract Points',
    'points': 'Points',
    'preview': 'Preview',
    'update_points': 'Update Points',
    'search_customers': 'Search customers...',
    'items_sold': 'Items Sold',
    'entry': 'Entry',
    'change_image': 'Change Image',
    'upload_image': 'Upload Image',
    'logout_confirm_message': 'Are you sure you want to sign out? You will need to log in again to access the system.',
    'close_menu': 'Close menu',
    'open_menu': 'Open menu',
    'show_sidebar': 'Show sidebar',
    'hide_sidebar': 'Hide sidebar',
    'manage_system_preferences': 'Manage system preferences',
    'toggle_theme_description': 'Toggle between light and dark themes',
    'choose_language_description': 'Choose your preferred language',
    'currency_rate': 'Currency Rate (USD→KHR)',
    'common_values': 'Common values: 4100, 4150',
    'wifi_info': 'WiFi Info',
    'wifi_info_description': 'Network name and password for receipts',
    'phone_number': 'Phone Number',
    'phone_number_description': 'Contact number for receipts',
    'order_fields': 'Order Fields',
    'order_fields_description': 'Customize fields for order forms',
    'field_type': 'Field Type',
    'field_label': 'Field Label',
    'field_options': 'Field Options',
    'value': 'Value',
    'save_schema': 'Save Schema',
    'saving': 'Saving...',
    'add_field': 'Add Field',
    'no_fields_configured': 'No fields configured',
    'label': 'Label',
    'key': 'Key',
    'auto_from_label': 'auto from label if empty',
    'no_options_yet': 'No options yet',
    // Reports specific
    'period': 'Period',
    'daily': 'Daily',
    'monthly': 'Monthly',
    'start_date': 'Start Date',
    'end_date': 'End Date',
    'transactions': 'transactions',
    'across_all_products': 'Across all products',
    'avg_order_value': 'Avg Order Value',
    'per_transaction': 'Per transaction',
    'margin': 'Margin',
    'top_selling_items': 'Top Selling Items',
    'sales_by_category': 'Sales by Category',
    'hourly_sales_pattern': 'Hourly Sales Pattern',
    'category_performance_report': 'Category Performance Report',
    'sales_breakdown_by_category': 'Sales breakdown by product category',
    'top_selling_items_report': 'Top Selling Items Report',
    'best_performing_products': 'Best performing products by revenue and quantity',
    'no_data_available': 'No data available',
    'no_data_for_filters': 'No data available for the selected filters',
    'revenue': 'Revenue',
    'hour': 'Hour',
    'avg_price': 'Avg Price',
    'quantity_sold': 'Quantity Sold',
    'unique_products': 'Unique Products',
    'avg_revenue_per_item': 'Avg Revenue/Item',
    'qty': 'Qty',
    'avg': 'avg',
    // Income-Expense specific
    'add_entry': 'Add Entry',
    'total_income': 'Total Income',
    'profit': 'Profit',
    'loss': 'Loss',
    'entries': 'entries',
    'filters': 'Filters',
    'all_types': 'All Types',
    'selected': 'selected',
    'this_action_cannot_be_undone': 'This action cannot be undone',
    'delete_selected': 'Delete Selected',
    'deleting': 'Deleting...',
    'edit_entry': 'Edit entry',
    'delete_entry': 'Delete entry',
    'no_entries_found': 'No entries found',
    'try_adjusting_filters': 'Try adjusting your filters to see more results.',
    'get_started_adding_entry': 'Get started by adding your first income or expense entry.',
    'add_new_entry': 'Add New Entry',
    'select_category': 'Select Category',
    'amount_dollar': 'Amount ($)',
    'add_entry_button': 'Add Entry',
    'are_you_sure_delete_entry': 'Are you sure you want to delete this entry?',
    'failed_to_save_entry': 'Failed to save entry',
    'failed_to_delete_entry': 'Failed to delete entry',
    'are_you_sure_delete_entries': 'Are you sure you want to delete {count} selected entries? This action cannot be undone.',
    'successfully_deleted_entries': 'Successfully deleted {count} entries',
    'failed_to_delete_entries': 'Failed to delete entries. Error: {error}',
    // Product card specific
    'customizable': 'Customizable',
    'product': 'Product',
    'low_stock': 'Low Stock',
    'in_stock': 'In Stock',
    'made_to_order': 'Made-to-Order',
    'custom': 'Custom',
    // Payment modal specific
    'pay_later': 'Pay Later',
    'qr_code': 'QR Code',
    'fixed_amount': 'Fixed Amount ($)',
    'percentage': 'Percentage (%)',
    'use_loyalty_points': 'Use Loyalty Points',
    'available': 'Available',
    'point_equals_dollar': '1 point = $1',
    'cash_received': 'Cash Received',
    'change': 'Change',
    'subtotal': 'Subtotal',
    // POS specific
    'pos_system': 'POS System',
    'add_to_cart': 'Add to Cart',
    'cart': 'Cart',
    'cart_empty': 'Cart is empty',
    'cart_total': 'Cart Total',
    'checkout': 'Checkout',
    'payment': 'Payment',
    'customer': 'Customer',
    'select_customer': 'Select Customer',
    'add_customer': 'Add Customer',
    'customer_lookup': 'Customer Lookup',
    'customer_name': 'Customer Name',
    'customer_phone': 'Customer Phone',
    'customer_member_card': 'Member Card',
    'quantity': 'Quantity',
    'tax': 'Tax',
    'discount': 'Discount',
    'total_amount': 'Total Amount',
    'payment_method': 'Payment Method',
    'cash': 'Cash',
    'card': 'Card',
    'receipt': 'Receipt',
    'order_completed': 'Order Completed',
    'order_number': 'Order Number',
    'order_date': 'Order Date',
    'order_time': 'Order Time',
    'order_status': 'Order Status',
    'order_notes': 'Order Notes',
    'customize_product': 'Customize Product',
    'product_customization': 'Product Customization',
    'size': 'Size',
    'small': 'Small',
    'medium': 'Medium',
    'large': 'Large',
    'sugar': 'Sugar',
    'less_sugar': 'Less Sugar',
    'normal_sugar': 'Normal Sugar',
    'extra_sugar': 'Extra Sugar',
    'add_ons': 'Add-ons',
    'add_on_name': 'Add-on Name',
    'add_on_price': 'Add-on Price',
    'remove_item': 'Remove Item',
    'clear_cart': 'Clear Cart',
    'processing_payment': 'Processing payment...',
    'payment_successful': 'Payment successful',
    'payment_failed': 'Payment failed',
    'insufficient_funds': 'Insufficient funds',
    'invalid_payment_amount': 'Invalid payment amount',
    'search_products_placeholder': 'Search products...',
    'no_products_available': 'No products available',
    'error_processing_payment': 'Error processing payment',
    'error_creating_order': 'Error creating order',
    'error_adding_to_cart': 'Error adding to cart',
    'error_removing_from_cart': 'Error removing from cart',
    'error_updating_cart': 'Error updating cart',
    'error_loading_customers': 'Error loading customers',
    'error_creating_customer': 'Error creating customer',
    'error_updating_customer': 'Error updating customer',
    'order_created_successfully': 'Order created successfully',
    'order_updated_successfully': 'Order updated successfully',
    'order_deleted_successfully': 'Order deleted successfully',
    'customer_created_successfully': 'Customer created successfully',
    'customer_updated_successfully': 'Customer updated successfully',
    'customer_deleted_successfully': 'Customer deleted successfully',
    // Orders specific
    'orders_management': 'Orders Management',
    'order_details': 'Order Details',
    'order_items': 'Order Items',
    'order_total': 'Order Total',
    'order_status_pending': 'Pending',
    'order_status_preparing': 'Preparing',
    'order_status_ready': 'Ready',
    'order_status_completed': 'Completed',
    'order_status_cancelled': 'Cancelled',
    'payment_status_paid': 'Paid',
    'payment_status_unpaid': 'Unpaid',
    'payment_status_partial': 'Partial',
    'edit_order': 'Edit Order',
    'delete_order': 'Delete Order',
    'mark_as_ready': 'Mark as Ready',
    'mark_as_completed': 'Mark as Completed',
    'cancel_order': 'Cancel Order',
    'order_created_at': 'Created At',
    'order_updated_at': 'Updated At',
    'order_completed_at': 'Completed At',
    'order_cancelled_at': 'Cancelled At',
    'order_items_count': 'Items Count',
    'order_customer_info': 'Customer Information',
    'order_payment_info': 'Payment Information',
    'order_metadata': 'Order Metadata',
    'order_custom_fields': 'Custom Fields',
    'order_actions': 'Order Actions',
    'order_history': 'Order History',
    'order_timeline': 'Order Timeline',
    'order_events': 'Order Events',
    'order_created': 'Order created',
    'order_updated': 'Order updated',
    'order_cancelled': 'Order cancelled',
    'order_payment_processed': 'Payment processed',
    'order_status_changed': 'Status changed',
    'order_notes_updated': 'Notes updated',
    'order_customer_updated': 'Customer updated',
    'order_items_updated': 'Items updated',
    'order_payment_updated': 'Payment updated',
    'order_metadata_updated': 'Metadata updated',
    'order_custom_fields_updated': 'Custom fields updated',
    'order_deleted': 'Order deleted',
    'order_restored': 'Order restored',
    'order_archived': 'Order archived',
    'order_unarchived': 'Order unarchived',
    'order_exported': 'Order exported',
    'order_imported': 'Order imported',
    'order_duplicated': 'Order duplicated',
    'order_merged': 'Order merged',
    'order_split': 'Order split',
    'order_refunded': 'Order refunded',
    'order_partially_refunded': 'Order partially refunded',
    'order_refund_cancelled': 'Refund cancelled',
    'order_refund_processed': 'Refund processed',
    'order_refund_failed': 'Refund failed',
    'order_payment_failed': 'Payment failed',
    'order_payment_retry': 'Payment retry',
    'order_payment_retry_failed': 'Payment retry failed',
    'order_payment_retry_successful': 'Payment retry successful',
    'order_payment_method_changed': 'Payment method changed',
    'order_payment_amount_changed': 'Payment amount changed',
    'order_payment_date_changed': 'Payment date changed',
    'order_payment_notes_changed': 'Payment notes changed',
    'order_payment_reference_changed': 'Payment reference changed',
    'order_payment_gateway_changed': 'Payment gateway changed',
    'order_payment_transaction_id_changed': 'Transaction ID changed',
    'order_payment_status_changed': 'Payment status changed',
    'order_payment_verified': 'Payment verified',
    'order_payment_unverified': 'Payment unverified',
    'order_payment_disputed': 'Payment disputed',
    'order_payment_dispute_resolved': 'Payment dispute resolved',
    'order_payment_chargeback': 'Payment chargeback',
    'order_payment_chargeback_resolved': 'Chargeback resolved',
    'order_payment_fraud_detected': 'Fraud detected',
    'order_payment_fraud_cleared': 'Fraud cleared',
    'order_payment_risk_assessed': 'Risk assessed',
    'order_payment_risk_approved': 'Risk approved',
    'order_payment_risk_rejected': 'Risk rejected',
    'order_payment_risk_escalated': 'Risk escalated',
    'order_payment_risk_cleared': 'Risk cleared',
    'order_payment_risk_flagged': 'Risk flagged',
    'order_payment_risk_unflagged': 'Risk unflagged',
    'order_payment_risk_reviewed': 'Risk reviewed',
    'order_payment_risk_approved_manual': 'Risk approved manually',
    'order_payment_risk_rejected_manual': 'Risk rejected manually',
    'order_payment_risk_escalated_manual': 'Risk escalated manually',
    'order_payment_risk_cleared_manual': 'Risk cleared manually',
    'order_payment_risk_flagged_manual': 'Risk flagged manually',
    'order_payment_risk_unflagged_manual': 'Risk unflagged manually',
    'order_payment_risk_reviewed_manual': 'Risk reviewed manually',
    'order_payment_risk_auto_approved': 'Risk auto approved',
    'order_payment_risk_auto_rejected': 'Risk auto rejected',
    'order_payment_risk_auto_escalated': 'Risk auto escalated',
    'order_payment_risk_auto_cleared': 'Risk auto cleared',
    'order_payment_risk_auto_flagged': 'Risk auto flagged',
    'order_payment_risk_auto_unflagged': 'Risk auto unflagged',
    'order_payment_risk_auto_reviewed': 'Risk auto reviewed',
    'order_payment_risk_auto_approved_manual': 'Risk auto approved manually',
    'order_payment_risk_auto_rejected_manual': 'Risk auto rejected manually',
    'order_payment_risk_auto_escalated_manual': 'Risk auto escalated manually',
    'order_payment_risk_auto_cleared_manual': 'Risk auto cleared manually',
    'order_payment_risk_auto_flagged_manual': 'Risk auto flagged manually',
    'order_payment_risk_auto_unflagged_manual': 'Risk auto unflagged manually',
    'order_payment_risk_auto_reviewed_manual': 'Risk auto reviewed manually',
  },
  km: {
    'dashboard': 'ផ្ទាំងគ្រប់គ្រង',
    'orders': 'ការបញ្ជាទិញ',
    'pos': 'Smach Cafe POS',
    'inventory': 'សន្លឹកស្តុក',
    'income_expense': 'ចំណូល និង ចំណាយ',
    'reports': 'របាយការណ៍',
    'customers': 'អតិថិជន',
    'settings': 'ការកំណត់',
    'welcome': 'សូមស្វាគមន៍',
    'logout': 'ចាកចេញ',
    'login': 'ចូល',
    'save': 'រក្សាទុក',
    'cancel': 'បោះបង់',
    'delete': 'លុប',
    'edit': 'កែប្រែ',
    'add': 'បន្ថែម',
    'loading': 'កំពុងផ្ទុក',
    'dark_mode': 'របៀបងងឹត',
    'language': 'ភាសា',
    'appearance': 'រូបរាង',
    // Extended translations
    'sign_in': 'ចូល',
    'username': 'ឈ្មោះអ្នកប្រើ',
    'password': 'ពាក្យសម្ងាត់',
    'demo_credentials': 'លេខសម្ងាត់សាកល្បង',
    'admin': 'អ្នកគ្រប់គ្រង',
    'staff': 'បុគ្គលិក',
    'signing_in': 'កំពុងចូល...',
    'total_revenue': 'ចំណូលសរុប',
    'total_expenses': 'ចំណាយសរុប',
    'net_profit': 'ចំណេញសុទ្ធ',
    'low_stock_alerts': 'ការជូនដំណឹងទំនិញស្ទើរអស់',
    'no_low_stock': 'មិនមានការជូនដំណឹងទំនិញស្ទើរអស់',
    'quick_actions': 'សកម្មភាពរហ័ស',
    'active_orders': 'ការបញ្ជាទិញសកម្ម',
    'no_orders_found': 'រកមិនឃើញការបញ្ជាទិញ',
    'table': 'តុ',
    'status': 'ស្ថានភាព',
    'payment_status': 'ស្ថានភាពបង់ប្រាក់',
    'total': 'សរុប',
    'actions': 'សកម្មភាព',
    'process_payment': 'ដំណើរការបង់ប្រាក់',
    'print_receipt': 'បោះពុម្ពបង្កាន់ដៃ',
    'confirm': 'បញ្ជាក់',
    'are_you_sure': 'តើអ្នកពិតជាចង់?',
    'name': 'ឈ្មោះ',
    'category': 'ប្រភេទ',
    'price': 'តម្លៃ',
    'stock': 'ស្តុក',
    'low_stock_threshold': 'កម្រិតទំនិញស្ទើរអស់',
    'description': 'ការពិពណ៌នា',
    'amount': 'ចំនួន',
    'date': 'កាលបរិច្ឆេទ',
    'type': 'ប្រភេទ',
    'income': 'ចំណូល',
    'expense': 'ចំណាយ',
    'filter': 'តម្រង',
    'search': 'ស្វែងរក',
    'clear': 'សម្អាត',
    'close': 'បិទ',
    'back': 'ត្រលប់',
    'next': 'បន្ទាប់',
    'previous': 'មុន',
    'submit': 'ដាក់ស្នើ',
    'reset': 'កំណត់ឡើងវិញ',
    'update': 'ធ្វើបច្ចុប្បន្នភាព',
    'create': 'បង្កើត',
    'remove': 'យកចេញ',
    'select': 'ជ្រើសរើស',
    'choose': 'ជ្រើសរើស',
    'upload': 'ផ្ទុកឡើង',
    'download': 'ទាញយក',
    'export': 'នាំចេញ',
    'import': 'នាំចូល',
    'view': 'មើល',
    'hide': 'លាក់',
    'show': 'បង្ហាញ',
    'open': 'បើក',
    'new': 'ថ្មី',
    'old': 'ចាស់',
    'all': 'ទាំងអស់',
    'none': 'គ្មាន',
    'yes': 'បាទ/ចាស',
    'no': 'ទេ',
    'ok': 'យល់ព្រម',
    'error': 'កំហុស',
    'success': 'ជោគជ័យ',
    'warning': 'ការព្រមាន',
    'info': 'ព័ត៌មាន',
    'pending': 'កំពុងរង់ចាំ',
    'completed': 'បានបញ្ចប់',
    'cancelled': 'បានលុបចោល',
    'paid': 'បានបង់',
    'unpaid': 'មិនទាន់បង់',
    'partial': 'បង់ផ្នែក',
    'preparing': 'កំពុងរៀបចំ',
    'ready': 'រួចរាល់',
    // Dashboard specific
    'todays_transactions': 'ប្រតិបត្តិការថ្ងៃនេះ',
    'todays_orders': 'ការបញ្ជាទិញថ្ងៃនេះ',
    'monthly_summary': 'សរុបប្រចាំខែ',
    'total_revenue_label': 'ចំណូលសរុប:',
    'total_expenses_label': 'ចំណាយសរុប:',
    'orders_label': 'ការបញ្ជាទិញ:',
    'net_profit_label': 'ចំណេញសុទ្ធ:',
    'low_stock_alerts_title': 'ការជូនដំណឹងទំនិញស្ទើរអស់',
    'no_low_stock_alerts': 'មិនមានការជូនដំណឹងទំនិញស្ទើរអស់',
    'quick_actions_title': 'សកម្មភាពរហ័ស',
    'new_order': 'ការបញ្ជាទិញថ្មី',
    'add_product': 'បន្ថែមផលិតផល',
    'view_reports': 'មើលរបាយការណ៍',
    'refresh': 'ផ្ទុកឡើងវិញ',
    'left': 'នៅសល់',
    'min': 'អប្បបរមា',
    // Inventory specific
    'add_product_modal': 'បន្ថែមផលិតផល',
    'edit_product_modal': 'កែប្រែផលិតផល',
    'product_name': 'ឈ្មោះផលិតផល',
    'product_price': 'តម្លៃផលិតផល',
    'product_stock': 'ស្តុកផលិតផល',
    'product_category': 'ប្រភេទផលិតផល',
    'product_description': 'ការពិពណ៌នាផលិតផល',
    'product_image': 'រូបភាពផលិតផល',
    'low_stock_threshold_label': 'កម្រិតទំនិញស្ទើរអស់',
    'product_options': 'ជម្រើសផលិតផល',
    'add_option': 'បន្ថែមជម្រើស',
    'option_name': 'ឈ្មោះជម្រើស',
    'option_type': 'ប្រភេទជម្រើស',
    'option_values': 'តម្លៃជម្រើស',
    'add_value': 'បន្ថែមតម្លៃ',
    'remove_option': 'យកជម្រើសចេញ',
    'manage_categories': 'គ្រប់គ្រងប្រភេទ',
    'add_category': 'បន្ថែមប្រភេទ',
    'category_name': 'ឈ្មោះប្រភេទ',
    'delete_product': 'លុបផលិតផល',
    'delete_product_confirm': 'តើអ្នកពិតជាចង់លុបផលិតផលនេះ?',
    'product_has_orders': 'ផលិតផលនេះមានការបញ្ជាទិញ និងមិនអាចលុបបាន។',
    'product_orders_count': 'ផលិតផលនេះត្រូវបានប្រើក្នុង {count} ការបញ្ជាទិញ។',
    'filter_by_category': 'តម្រងតាមប្រភេទ',
    'all_categories': 'ប្រភេទទាំងអស់',
    'search_products': 'ស្វែងរកផលិតផល...',
    'no_products_found': 'រកមិនឃើញផលិតផល',
    'product_created': 'បានបង្កើតផលិតផលដោយជោគជ័យ',
    'product_updated': 'បានធ្វើបច្ចុប្បន្នភាពផលិតផលដោយជោគជ័យ',
    'product_deleted': 'បានលុបផលិតផលដោយជោគជ័យ',
    'error_creating_product': 'កំហុសក្នុងការបង្កើតផលិតផល',
    'error_updating_product': 'កំហុសក្នុងការធ្វើបច្ចុប្បន្នភាពផលិតផល',
    'error_deleting_product': 'កំហុសក្នុងការលុបផលិតផល',
    'error_loading_products': 'កំហុសក្នុងការផ្ទុកផលិតផល',
    'error_loading_categories': 'កំហុសក្នុងការផ្ទុកប្រភេទ',
    'error_saving_categories': 'កំហុសក្នុងការរក្សាទុកប្រភេទ',
    'category_created': 'បានបង្កើតប្រភេទដោយជោគជ័យ',
    'category_updated': 'បានធ្វើបច្ចុប្បន្នភាពប្រភេទដោយជោគជ័យ',
    'category_deleted': 'បានលុបប្រភេទដោយជោគជ័យ',
    'duplicate_category': 'ប្រភេទមានរួចហើយ',
    'invalid_category_name': 'សូមបញ្ចូលឈ្មោះប្រភេទត្រឹមត្រូវ',
    'required_field': 'វាលនេះចាំបាច់',
    'invalid_price': 'សូមបញ្ចូលតម្លៃត្រឹមត្រូវ',
    'invalid_stock': 'សូមបញ្ចូលបរិមាណស្តុកត្រឹមត្រូវ',
    'invalid_low_stock_threshold': 'សូមបញ្ចូលកម្រិតទំនិញស្ទើរអស់ត្រឹមត្រូវ',
    'image_upload_error': 'កំហុសក្នុងការផ្ទុកឡើងរូបភាព',
    'image_too_large': 'ឯកសាររូបភាពធំពេក',
    'invalid_image_format': 'ទម្រង់រូបភាពមិនត្រឹមត្រូវ',
    'loading_products': 'កំពុងផ្ទុកផលិតផល...',
    'saving_product': 'កំពុងរក្សាទុកផលិតផល...',
    'deleting_product': 'កំពុងលុបផលិតផល...',
    'loading_categories': 'កំពុងផ្ទុកប្រភេទ...',
    'saving_categories': 'កំពុងរក្សាទុកប្រភេទ...',
    'basic_information': 'ព័ត៌មានមូលដ្ឋាន',
    'total_customers': 'អតិថិជនសរុប',
    'total_loyalty_points': 'ពិន្ទុសម្ពាធសរុប',
    'avg_points_per_customer': 'ពិន្ទុមធ្យមក្នុងមួយអតិថិជន',
    'loyalty_points': 'ពិន្ទុសម្ពាធ',
    'member_card': 'កាតសមាជិក',
    'phone': 'ទូរស័ព្ទ',
    'manage_points': 'គ្រប់គ្រងពិន្ទុ',
    'add_new_customer': 'បន្ថែមអតិថិជនថ្មី',
    'manage_loyalty_points': 'គ្រប់គ្រងពិន្ទុសម្ពាធ',
    'current_points': 'ពិន្ទុបច្ចុប្បន្ន',
    'operation': 'ប្រតិបត្តិការ',
    'add_points': 'បន្ថែមពិន្ទុ',
    'subtract_points': 'ដកពិន្ទុ',
    'points': 'ពិន្ទុ',
    'preview': 'មើលជាមុន',
    'update_points': 'ធ្វើបច្ចុប្បន្នភាពពិន្ទុ',
    'search_customers': 'ស្វែងរកអតិថិជន...',
    'items_sold': 'ទំនិញដែលលក់',
    'entry': 'ធាតុ',
    'change_image': 'ប្ដូររូបភាព',
    'upload_image': 'ផ្ទុកឡើងរូបភាព',
    'logout_confirm_message': 'តើអ្នកពិតជាចង់ចាកចេញ? អ្នកនឹងត្រូវចូលម្តងទៀតដើម្បីចូលប្រើប្រព័ន្ធ។',
    'close_menu': 'បិទម៉ឺនុយ',
    'open_menu': 'បើកម៉ឺនុយ',
    'show_sidebar': 'បង្ហាញរបារចំហៀង',
    'hide_sidebar': 'លាក់របារចំហៀង',
    'manage_system_preferences': 'គ្រប់គ្រងការកំណត់ប្រព័ន្ធ',
    'toggle_theme_description': 'ប្ដូររវាងរបៀបពន្លឺ និងងងឹត',
    'choose_language_description': 'ជ្រើសរើសភាសាដែលអ្នកចូលចិត្ត',
    'currency_rate': 'អត្រាប្រាក់ (USD→KHR)',
    'common_values': 'តម្លៃទូទៅ: 4100, 4150',
    'wifi_info': 'ព័ត៌មាន WiFi',
    'wifi_info_description': 'ឈ្មោះបណ្តាញ និងពាក្យសម្ងាត់សម្រាប់បង្កាន់ដៃ',
    'phone_number': 'លេខទូរស័ព្ទ',
    'phone_number_description': 'លេខទំនាក់ទំនងសម្រាប់បង្កាន់ដៃ',
    'order_fields': 'វាលការបញ្ជាទិញ',
    'order_fields_description': 'ប្ដូរតម្លៃវាលសម្រាប់ទម្រង់ការបញ្ជាទិញ',
    'field_type': 'ប្រភេទវាល',
    'field_label': 'ស្លាកវាល',
    'field_options': 'ជម្រើសវាល',
    'value': 'តម្លៃ',
    'save_schema': 'រក្សាទុកគ្រោងការណ៍',
    'saving': 'កំពុងរក្សាទុក...',
    'add_field': 'បន្ថែមវាល',
    'no_fields_configured': 'មិនមានវាលដែលបានកំណត់',
    'label': 'ស្លាក',
    'key': 'គន្លឹះ',
    'auto_from_label': 'ដោយស្វ័យប្រវត្តិពីស្លាកប្រសិនបើទទេ',
    'no_options_yet': 'មិនមានជម្រើសនៅឡើយ',
    // Reports specific
    'period': 'រយៈពេល',
    'daily': 'ប្រចាំថ្ងៃ',
    'monthly': 'ប្រចាំខែ',
    'start_date': 'កាលបរិច្ឆេទចាប់ផ្តើម',
    'end_date': 'កាលបរិច្ឆេទបញ្ចប់',
    'transactions': 'ប្រតិបត្តិការ',
    'across_all_products': 'ទូទាំងផលិតផលទាំងអស់',
    'avg_order_value': 'តម្លៃការបញ្ជាទិញជាមធ្យម',
    'per_transaction': 'ក្នុងមួយប្រតិបត្តិការ',
    'margin': 'ចំណូល',
    'top_selling_items': 'ផលិតផលលក់ដាច់បំផុត',
    'sales_by_category': 'ការលក់តាមប្រភេទ',
    'hourly_sales_pattern': 'លំនាំការលក់ប្រចាំម៉ោង',
    'category_performance_report': 'របាយការណ៍ដំណើរការប្រភេទ',
    'sales_breakdown_by_category': 'ការបំបែកការលក់តាមប្រភេទផលិតផល',
    'top_selling_items_report': 'របាយការណ៍ផលិតផលលក់ដាច់បំផុត',
    'best_performing_products': 'ផលិតផលដំណើរការល្អបំផុតតាមចំណូល និងបរិមាណ',
    'no_data_available': 'មិនមានទិន្នន័យ',
    'no_data_for_filters': 'មិនមានទិន្នន័យសម្រាប់តម្រងដែលបានជ្រើសរើស',
    'revenue': 'ចំណូល',
    'hour': 'ម៉ោង',
    'avg_price': 'តម្លៃជាមធ្យម',
    'quantity_sold': 'បរិមាណលក់',
    'unique_products': 'ផលិតផលពិសេស',
    'avg_revenue_per_item': 'ចំណូលជាមធ្យមក្នុងមួយធាតុ',
    'qty': 'បរិមាណ',
    'avg': 'ជាមធ្យម',
    // Income-Expense specific
    'add_entry': 'បន្ថែមធាតុ',
    'total_income': 'ចំណូលសរុប',
    'profit': 'ចំណេញ',
    'loss': 'ខាត',
    'entries': 'ធាតុ',
    'filters': 'តម្រង',
    'all_types': 'ប្រភេទទាំងអស់',
    'selected': 'បានជ្រើសរើស',
    'this_action_cannot_be_undone': 'សកម្មភាពនេះមិនអាចត្រូវបានបញ្ច្រាស់',
    'delete_selected': 'លុបដែលបានជ្រើសរើស',
    'deleting': 'កំពុងលុប...',
    'edit_entry': 'កែសម្រួលធាតុ',
    'delete_entry': 'លុបធាតុ',
    'no_entries_found': 'មិនឃើញធាតុ',
    'try_adjusting_filters': 'សូមផ្លាស់ប្តូរតម្រងរបស់អ្នកដើម្បីមើលលទ្ធផលបន្ថែម។',
    'get_started_adding_entry': 'ចាប់ផ្តើមដោយបន្ថែមធាតុចំណូល ឬចំណាយដំបូងរបស់អ្នក។',
    'add_new_entry': 'បន្ថែមធាតុថ្មី',
    'select_category': 'ជ្រើសរើសប្រភេទ',
    'amount_dollar': 'ចំនួន ($)',
    'add_entry_button': 'បន្ថែមធាតុ',
    'are_you_sure_delete_entry': 'តើអ្នកពិតជាចង់លុបធាតុនេះ?',
    'failed_to_save_entry': 'មិនអាចរក្សាទុកធាតុ',
    'failed_to_delete_entry': 'មិនអាចលុបធាតុ',
    'are_you_sure_delete_entries': 'តើអ្នកពិតជាចង់លុប {count} ធាតុដែលបានជ្រើសរើស? សកម្មភាពនេះមិនអាចត្រូវបានបញ្ច្រាស់។',
    'successfully_deleted_entries': 'លុប {count} ធាតុដោយជោគជ័យ',
    'failed_to_delete_entries': 'មិនអាចលុបធាតុ។ កំហុស: {error}',
    // Product card specific
    'customizable': 'អាចប្ដូរតម្លៃបាន',
    'product': 'ផលិតផល',
    'low_stock': 'ស្តុកទាប',
    'in_stock': 'មានស្តុក',
    'made_to_order': 'ធ្វើតាមការបញ្ជាទិញ',
    'custom': 'ផ្ទាល់',
    // Payment modal specific
    'payment_method': 'វិធីសាស្ត្រទូទាត់',
    'pay_later': 'ទូទាត់ពេលក្រោយ',
    'cash': 'សាច់ប្រាក់',
    'qr_code': 'កូដ QR',
    'discount': 'បញ្ចុះតម្លៃ',
    'fixed_amount': 'ចំនួនថេរ ($)',
    'percentage': 'ភាគរយ (%)',
    'use_loyalty_points': 'ប្រើពិន្ទុស្នាព្រះហស្ថ',
    'available': 'មាន',
    'point_equals_dollar': '1 ពិន្ទុ = $1',
    'cash_received': 'សាច់ប្រាក់ទទួលបាន',
    'change': 'អាប់',
    'subtotal': 'សរុបរង',
    // POS specific
    'pos_system': 'ប្រព័ន្ធ POS',
    'add_to_cart': 'បន្ថែមទៅកាត',
    'cart': 'កាត',
    'cart_empty': 'កាតទទេ',
    'cart_total': 'សរុបកាត',
    'checkout': 'ពិនិត្យចេញ',
    'payment': 'បង់ប្រាក់',
    'customer': 'អតិថិជន',
    'select_customer': 'ជ្រើសរើសអតិថិជន',
    'add_customer': 'បន្ថែមអតិថិជន',
    'customer_lookup': 'ស្វែងរកអតិថិជន',
    'customer_name': 'ឈ្មោះអតិថិជន',
    'customer_phone': 'ទូរស័ព្ទអតិថិជន',
    'customer_member_card': 'កាតសមាជិក',
    'quantity': 'បរិមាណ',
    'tax': 'ពន្ធ',
    'total_amount': 'ចំនួនសរុប',
    'card': 'កាត',
    'receipt': 'បង្កាន់ដៃ',
    'order_completed': 'ការបញ្ជាទិញបានបញ្ចប់',
    'order_number': 'លេខការបញ្ជាទិញ',
    'order_date': 'កាលបរិច្ឆេទការបញ្ជាទិញ',
    'order_time': 'ពេលវេលាការបញ្ជាទិញ',
    'order_status': 'ស្ថានភាពការបញ្ជាទិញ',
    'order_notes': 'កំណត់សម្គាល់ការបញ្ជាទិញ',
    'customize_product': 'ប្ដូរតម្លៃផលិតផល',
    'product_customization': 'ការប្ដូរតម្លៃផលិតផល',
    'size': 'ទំហំ',
    'small': 'តូច',
    'medium': 'មធ្យម',
    'large': 'ធំ',
    'sugar': 'ស្ករស',
    'less_sugar': 'ស្ករសតិច',
    'normal_sugar': 'ស្ករសធម្មតា',
    'extra_sugar': 'ស្ករសច្រើន',
    'add_ons': 'បន្ថែម',
    'add_on_name': 'ឈ្មោះបន្ថែម',
    'add_on_price': 'តម្លៃបន្ថែម',
    'remove_item': 'យកធាតុចេញ',
    'clear_cart': 'សម្អាតកាត',
    'processing_payment': 'កំពុងដំណើរការបង់ប្រាក់...',
    'payment_successful': 'បង់ប្រាក់ដោយជោគជ័យ',
    'payment_failed': 'បង់ប្រាក់បរាជ័យ',
    'insufficient_funds': 'មូលនិធិមិនគ្រប់គ្រាន់',
    'invalid_payment_amount': 'ចំនួនបង់ប្រាក់មិនត្រឹមត្រូវ',
    'search_products_placeholder': 'ស្វែងរកផលិតផល...',
    'no_products_available': 'គ្មានផលិតផល',
    'error_processing_payment': 'កំហុសក្នុងការដំណើរការបង់ប្រាក់',
    'error_creating_order': 'កំហុសក្នុងការបង្កើតការបញ្ជាទិញ',
    'error_adding_to_cart': 'កំហុសក្នុងការបន្ថែមទៅកាត',
    'error_removing_from_cart': 'កំហុសក្នុងការយកចេញពីកាត',
    'error_updating_cart': 'កំហុសក្នុងការធ្វើបច្ចុប្បន្នភាពកាត',
    'error_loading_customers': 'កំហុសក្នុងការផ្ទុកអតិថិជន',
    'error_creating_customer': 'កំហុសក្នុងការបង្កើតអតិថិជន',
    'error_updating_customer': 'កំហុសក្នុងការធ្វើបច្ចុប្បន្នភាពអតិថិជន',
    'order_created_successfully': 'បានបង្កើតការបញ្ជាទិញដោយជោគជ័យ',
    'order_updated_successfully': 'បានធ្វើបច្ចុប្បន្នភាពការបញ្ជាទិញដោយជោគជ័យ',
    'order_deleted_successfully': 'បានលុបការបញ្ជាទិញដោយជោគជ័យ',
    'customer_created_successfully': 'បានបង្កើតអតិថិជនដោយជោគជ័យ',
    'customer_updated_successfully': 'បានធ្វើបច្ចុប្បន្នភាពអតិថិជនដោយជោគជ័យ',
    'customer_deleted_successfully': 'បានលុបអតិថិជនដោយជោគជ័យ',
  }
};

const languageNames: Record<Language, string> = {
  en: 'English',
  km: 'ខ្មែរ',
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    // Check localStorage first
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && savedLanguage in translations) {
      return savedLanguage;
    }
    
    // Check browser language
    const browserLang = navigator.language.split('-')[0] as Language;
    if (browserLang in translations) {
      return browserLang;
    }
    
    return 'en';
  });

  useEffect(() => {
    // Save to localStorage
    localStorage.setItem('language', language);
    
    // Set document language
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export { languageNames };
export type { Language };
